Naive Bays Algorithm

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Pearl_Jam_Tour2.csv', encoding='unicode_escape')

In [3]:
df

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out
0,13515000,North America,8000,Monday,1,0
1,13515000,North America,8000,Tuesday,1,1
2,12478447,North America,15000,Wednesday,1,1
3,12478447,North America,15000,Thursday,1,0
4,27500000,North America,11000,Friday,1,1
5,27500000,North America,11000,Saturday,1,1
6,2187526,North America,14900,Sunday,1,1
7,21515000,North America,12300,Monday,1,1
8,3076047,North America,22800,Tuesday,0,0
9,9120350,North America,33200,Wednesday,0,1
10,12678079,North America,39100,Thursday,1,1
11,12678079,North America,39100,Friday,1,1
12,6747815,North America,14900,Sunday,0,0
13,9736586,Europe,30500,Sunday,0,0
14,15519267,Europe,18700,Monday,1,0
15,5367206,Europe,21000,Tuesday,1,1
16,5367206,Europe,21000,Wednesday,1,1
17,10782810,Europe,26500,Thursday,0,1
18,3331000,Europe,23200,Friday,0,1
19,2870733,Europe,8000,Saturday,0,1
20,5635127,Europe,20200,Sunday,0,1
21,14862000,Europe,11300,Monday,0,1
22,883305,Europe,15600,Tuesday,0,0
23,14910352,Europe,33900,Wednesday,0,0
24,2581079,Europe,12900,Thursday,0,1
25,31400000,North America,26700,Friday,1,1
26,31400000,North America,26700,Saturday,1,1
27,2693976,North America,34600,Sunday,0,0
28,76750000,North America,8400,Monday,1,1
29,9751717,North America,8400,Tuesday,0,0
30,1793579,North America,18300,Wednesday,0,1
31,4397073,South America,29100,Thursday,1,1
32,4397073,South America,26400,Friday,1,0
33,3520031,South America,33900,Saturday,0,0
34,7592871,South America,15600,Sunday,0,0
35,1808000,South America,15000,Monday,0,1
36,794128,South America,21000,Tuesday,0,0
37,7592871,Asia,28500,Wednesday,1,1
38,7592871,Asia,28500,Thursday,1,1
39,13698000,Asia,28500,Friday,1,1
40,13698000,Asia,23200,Saturday,1,1
41,13698000,Asia,23200,Sunday,1,0

In [4]:
df2 = pd.get_dummies(df[['Continent','Day of Week']])

In [5]:
df2

,Continent_Asia,Continent_Europe,Continent_North America,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,False,False,True,False,False,True,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,True,False
2,False,False,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,False,False,True,False,False
4,False,False,True,False,True,False,False,False,False,False,False
5,False,False,True,False,False,False,True,False,False,False,False
6,False,False,True,False,False,False,False,True,False,False,False
7,False,False,True,False,False,True,False,False,False,False,False
8,False,False,True,False,False,False,False,False,False,True,False
9,False,False,True,False,False,False,False,False,False,False,True
10,False,False,True,False,False,False,False,False,True,False,False
11,False,False,True,False,True,False,False,False,False,False,False
12,False,False,True,False,False,False,False,True,False,False,False
13,False,True,False,False,False,False,False,True,False,False,False
14,False,True,False,False,False,True,False,False,False,False,False
15,False,True,False,False,False,False,False,False,False,True,False
16,False,True,False,False,False,False,False,False,False,False,True
17,False,True,False,False,False,False,False,False,True,False,False
18,False,True,False,False,True,False,False,False,False,False,False
19,False,True,False,False,False,False,True,False,False,False,False
20,False,True,False,False,False,False,False,True,False,False,False
21,False,True,False,False,False,True,False,False,False,False,False
22,False,True,False,False,False,False,False,False,False,True,False
23,False,True,False,False,False,False,False,False,False,False,True
24,False,True,False,False,False,False,False,False,True,False,False
25,False,False,True,False,True,False,False,False,False,False,False
26,False,False,True,False,False,False,True,False,False,False,False
27,False,False,True,False,False,False,False,True,False,False,False
28,False,False,True,False,False,True,False,False,False,False,False
29,False,False,True,False,False,False,False,False,False,True,False
30,False,False,True,False,False,False,False,False,False,False,True
31,False,False,False,True,False,False,False,False,True,False,False
32,False,False,False,True,True,False,False,False,False,False,False
33,False,False,False,True,False,False,True,False,False,False,False
34,False,False,False,True,False,False,False,True,False,False,False
35,False,False,False,True,False,True,False,False,False,False,False
36,False,False,False,True,False,False,False,False,False,True,False
37,True,False,False,False,False,False,False,False,False,False,True
38,True,False,False,False,False,False,False,False,True,False,False
39,True,False,False,False,True,False,False,False,False,False,False
40,True,False,False,False,False,False,True,False,False,False,False
41,True,False,False,False,False,False,False,True,False,False,False