Naive Bays Algorithm

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Pearl_Jam_Tour2.csv', encoding='unicode_escape')

In [3]:
df

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out
0,13515000,North America,8000,Monday,1,0
1,13515000,North America,8000,Tuesday,1,1
2,12478447,North America,15000,Wednesday,1,1
3,12478447,North America,15000,Thursday,1,0
4,27500000,North America,11000,Friday,1,1
5,27500000,North America,11000,Saturday,1,1
6,2187526,North America,14900,Sunday,1,1
7,21515000,North America,12300,Monday,1,1
8,3076047,North America,22800,Tuesday,0,0
9,9120350,North America,33200,Wednesday,0,1
10,12678079,North America,39100,Thursday,1,1
11,12678079,North America,39100,Friday,1,1
12,6747815,North America,14900,Sunday,0,0
13,9736586,Europe,30500,Sunday,0,0
14,15519267,Europe,18700,Monday,1,0
15,5367206,Europe,21000,Tuesday,1,1
16,5367206,Europe,21000,Wednesday,1,1
17,10782810,Europe,26500,Thursday,0,1
18,3331000,Europe,23200,Friday,0,1
19,2870733,Europe,8000,Saturday,0,1
20,5635127,Europe,20200,Sunday,0,1
21,14862000,Europe,11300,Monday,0,1
22,883305,Europe,15600,Tuesday,0,0
23,14910352,Europe,33900,Wednesday,0,0
24,2581079,Europe,12900,Thursday,0,1
25,31400000,North America,26700,Friday,1,1
26,31400000,North America,26700,Saturday,1,1
27,2693976,North America,34600,Sunday,0,0
28,76750000,North America,8400,Monday,1,1
29,9751717,North America,8400,Tuesday,0,0
30,1793579,North America,18300,Wednesday,0,1
31,4397073,South America,29100,Thursday,1,1
32,4397073,South America,26400,Friday,1,0
33,3520031,South America,33900,Saturday,0,0
34,7592871,South America,15600,Sunday,0,0
35,1808000,South America,15000,Monday,0,1
36,794128,South America,21000,Tuesday,0,0
37,7592871,Asia,28500,Wednesday,1,1
38,7592871,Asia,28500,Thursday,1,1
39,13698000,Asia,28500,Friday,1,1
40,13698000,Asia,23200,Saturday,1,1
41,13698000,Asia,23200,Sunday,1,0

In [4]:
df2 = pd.get_dummies(df[['Continent','Day of Week']])

In [5]:
df2= pd.get_dummies(df, columns=['Continent', 'Day of Week'])
df2 = df2.astype(int)

In [6]:
df2

,City Population,Venue Capacity,Multiple Concerts,Sold Out,Continent_Asia,Continent_Europe,Continent_North America,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,13515000,8000,1,0,0,0,1,0,0,1,0,0,0,0,0
1,13515000,8000,1,1,0,0,1,0,0,0,0,0,0,1,0
2,12478447,15000,1,1,0,0,1,0,0,0,0,0,0,0,1
3,12478447,15000,1,0,0,0,1,0,0,0,0,0,1,0,0
4,27500000,11000,1,1,0,0,1,0,1,0,0,0,0,0,0
5,27500000,11000,1,1,0,0,1,0,0,0,1,0,0,0,0
6,2187526,14900,1,1,0,0,1,0,0,0,0,1,0,0,0
7,21515000,12300,1,1,0,0,1,0,0,1,0,0,0,0,0
8,3076047,22800,0,0,0,0,1,0,0,0,0,0,0,1,0
9,9120350,33200,0,1,0,0,1,0,0,0,0,0,0,0,1
10,12678079,39100,1,1,0,0,1,0,0,0,0,0,1,0,0
11,12678079,39100,1,1,0,0,1,0,1,0,0,0,0,0,0
12,6747815,14900,0,0,0,0,1,0,0,0,0,1,0,0,0
13,9736586,30500,0,0,0,1,0,0,0,0,0,1,0,0,0
14,15519267,18700,1,0,0,1,0,0,0,1,0,0,0,0,0
15,5367206,21000,1,1,0,1,0,0,0,0,0,0,0,1,0
16,5367206,21000,1,1,0,1,0,0,0,0,0,0,0,0,1
17,10782810,26500,0,1,0,1,0,0,0,0,0,0,1,0,0
18,3331000,23200,0,1,0,1,0,0,1,0,0,0,0,0,0
19,2870733,8000,0,1,0,1,0,0,0,0,1,0,0,0,0
20,5635127,20200,0,1,0,1,0,0,0,0,0,1,0,0,0
21,14862000,11300,0,1,0,1,0,0,0,1,0,0,0,0,0
22,883305,15600,0,0,0,1,0,0,0,0,0,0,0,1,0
23,14910352,33900,0,0,0,1,0,0,0,0,0,0,0,0,1
24,2581079,12900,0,1,0,1,0,0,0,0,0,0,1,0,0
25,31400000,26700,1,1,0,0,1,0,1,0,0,0,0,0,0
26,31400000,26700,1,1,0,0,1,0,0,0,1,0,0,0,0
27,2693976,34600,0,0,0,0,1,0,0,0,0,1,0,0,0
28,76750000,8400,1,1,0,0,1,0,0,1,0,0,0,0,0
29,9751717,8400,0,0,0,0,1,0,0,0,0,0,0,1,0
30,1793579,18300,0,1,0,0,1,0,0,0,0,0,0,0,1
31,4397073,29100,1,1,0,0,0,1,0,0,0,0,1,0,0
32,4397073,26400,1,0,0,0,0,1,1,0,0,0,0,0,0
33,3520031,33900,0,0,0,0,0,1,0,0,1,0,0,0,0
34,7592871,15600,0,0,0,0,0,1,0,0,0,1,0,0,0
35,1808000,15000,0,1,0,0,0,1,0,1,0,0,0,0,0
36,794128,21000,0,0,0,0,0,1,0,0,0,0,0,1,0
37,7592871,28500,1,1,1,0,0,0,0,0,0,0,0,0,1
38,7592871,28500,1,1,1,0,0,0,0,0,0,0,1,0,0
39,13698000,28500,1,1,1,0,0,0,1,0,0,0,0,0,0
40,13698000,23200,1,1,1,0,0,0,0,0,1,0,0,0,0
41,13698000,23200,1,0,1,0,0,0,0,0,0,1,0,0,0

In [7]:
df3 = pd.concat([df,df2],axis=1)

In [8]:
df3

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out,City Population,Venue Capacity,Multiple Concerts,Sold Out,...,Continent_Europe,Continent_North America,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,13515000,North America,8000,Monday,1,0,13515000,8000,1,0,...,0,1,0,0,1,0,0,0,0,0
1,13515000,North America,8000,Tuesday,1,1,13515000,8000,1,1,...,0,1,0,0,0,0,0,0,1,0
2,12478447,North America,15000,Wednesday,1,1,12478447,15000,1,1,...,0,1,0,0,0,0,0,0,0,1
3,12478447,North America,15000,Thursday,1,0,12478447,15000,1,0,...,0,1,0,0,0,0,0,1,0,0
4,27500000,North America,11000,Friday,1,1,27500000,11000,1,1,...,0,1,0,1,0,0,0,0,0,0
5,27500000,North America,11000,Saturday,1,1,27500000,11000,1,1,...,0,1,0,0,0,1,0,0,0,0
6,2187526,North America,14900,Sunday,1,1,2187526,14900,1,1,...,0,1,0,0,0,0,1,0,0,0
7,21515000,North America,12300,Monday,1,1,21515000,12300,1,1,...,0,1,0,0,1,0,0,0,0,0
8,3076047,North America,22800,Tuesday,0,0,3076047,22800,0,0,...,0,1,0,0,0,0,0,0,1,0
9,9120350,North America,33200,Wednesday,0,1,9120350,33200,0,1,...,0,1,0,0,0,0,0,0,0,1
10,12678079,North America,39100,Thursday,1,1,12678079,39100,1,1,...,0,1,0,0,0,0,0,1,0,0
11,12678079,North America,39100,Friday,1,1,12678079,39100,1,1,...,0,1,0,1,0,0,0,0,0,0
12,6747815,North America,14900,Sunday,0,0,6747815,14900,0,0,...,0,1,0,0,0,0,1,0,0,0
13,9736586,Europe,30500,Sunday,0,0,9736586,30500,0,0,...,1,0,0,0,0,0,1,0,0,0
14,15519267,Europe,18700,Monday,1,0,15519267,18700,1,0,...,1,0,0,0,1,0,0,0,0,0
15,5367206,Europe,21000,Tuesday,1,1,5367206,21000,1,1,...,1,0,0,0,0,0,0,0,1,0
16,5367206,Europe,21000,Wednesday,1,1,5367206,21000,1,1,...,1,0,0,0,0,0,0,0,0,1
17,10782810,Europe,26500,Thursday,0,1,10782810,26500,0,1,...,1,0,0,0,0,0,0,1,0,0
18,3331000,Europe,23200,Friday,0,1,3331000,23200,0,1,...,1,0,0,1,0,0,0,0,0,0
19,2870733,Europe,8000,Saturday,0,1,2870733,8000,0,1,...,1,0,0,0,0,1,0,0,0,0
20,5635127,Europe,20200,Sunday,0,1,5635127,20200,0,1,...,1,0,0,0,0,0,1,0,0,0
21,14862000,Europe,11300,Monday,0,1,14862000,11300,0,1,...,1,0,0,0,1,0,0,0,0,0
22,883305,Europe,15600,Tuesday,0,0,883305,15600,0,0,...,1,0,0,0,0,0,0,0,1,0
23,14910352,Europe,33900,Wednesday,0,0,14910352,33900,0,0,...,1,0,0,0,0,0,0,0,0,1
24,2581079,Europe,12900,Thursday,0,1,2581079,12900,0,1,...,1,0,0,0,0,0,0,1,0,0
25,31400000,North America,26700,Friday,1,1,31400000,26700,1,1,...,0,1,0,1,0,0,0,0,0,0
26,31400000,North America,26700,Saturday,1,1,31400000,26700,1,1,...,0,1,0,0,0,1,0,0,0,0
27,2693976,North America,34600,Sunday,0,0,2693976,34600,0,0,...,0,1,0,0,0,0,1,0,0,0
28,76750000,North America,8400,Monday,1,1,76750000,8400,1,1,...,0,1,0,0,1,0,0,0,0,0
29,9751717,North America,8400,Tuesday,0,0,9751717,8400,0,0,...,0,1,0,0,0,0,0,0,1,0
30,1793579,North America,18300,Wednesday,0,1,1793579,18300,0,1,...,0,1,0,0,0,0,0,0,0,1
31,4397073,South America,29100,Thursday,1,1,4397073,29100,1,1,...,0,0,1,0,0,0,0,1,0,0
32,4397073,South America,26400,Friday,1,0,4397073,26400,1,0,...,0,0,1,1,0,0,0,0,0,0
33,3520031,South America,33900,Saturday,0,0,3520031,33900,0,0,...,0,0,1,0,0,1,0,0,0,0
34,7592871,South America,15600,Sunday,0,0,7592871,15600,0,0,...,0,0,1,0,0,0,1,0,0,0
35,1808000,South America,15000,Monday,0,1,1808000,15000,0,1,...,0,0,1,0,1,0,0,0,0,0
36,794128,South America,21000,Tuesday,0,0,794128,21000,0,0,...,0,0,1,0,0,0,0,0,1,0
37,7592871,Asia,28500,Wednesday,1,1,7592871,28500,1,1,...,0,0,0,0,0,0,0,0,0,1
38,7592871,Asia,28500,Thursday,1,1,7592871,28500,1,1,...,0,0,0,0,0,0,0,1,0,0
39,13698000,Asia,28500,Friday,1,1,13698000,28500,1,1,...,0,0,0,1,0,0,0,0,0,0
40,13698000,Asia,23200,Saturday,1,1,13698000,23200,1,1,...,0,0,0,0,0,1,0,0,0,0
41,13698000,Asia,23200,Sunday,1,0,13698000,23200,1,0,...,0,0,0,0,0,0,1,0,0,0

In [9]:
df4 = df3.drop(['Continent','Day of Week'],axis=1)

In [10]:
df4

,City Population,Venue Capacity,Multiple Concerts,Sold Out,City Population,Venue Capacity,Multiple Concerts,Sold Out,Continent_Asia,Continent_Europe,Continent_North America,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,13515000,8000,1,0,13515000,8000,1,0,0,0,1,0,0,1,0,0,0,0,0
1,13515000,8000,1,1,13515000,8000,1,1,0,0,1,0,0,0,0,0,0,1,0
2,12478447,15000,1,1,12478447,15000,1,1,0,0,1,0,0,0,0,0,0,0,1
3,12478447,15000,1,0,12478447,15000,1,0,0,0,1,0,0,0,0,0,1,0,0
4,27500000,11000,1,1,27500000,11000,1,1,0,0,1,0,1,0,0,0,0,0,0
5,27500000,11000,1,1,27500000,11000,1,1,0,0,1,0,0,0,1,0,0,0,0
6,2187526,14900,1,1,2187526,14900,1,1,0,0,1,0,0,0,0,1,0,0,0
7,21515000,12300,1,1,21515000,12300,1,1,0,0,1,0,0,1,0,0,0,0,0
8,3076047,22800,0,0,3076047,22800,0,0,0,0,1,0,0,0,0,0,0,1,0
9,9120350,33200,0,1,9120350,33200,0,1,0,0,1,0,0,0,0,0,0,0,1
10,12678079,39100,1,1,12678079,39100,1,1,0,0,1,0,0,0,0,0,1,0,0
11,12678079,39100,1,1,12678079,39100,1,1,0,0,1,0,1,0,0,0,0,0,0
12,6747815,14900,0,0,6747815,14900,0,0,0,0,1,0,0,0,0,1,0,0,0
13,9736586,30500,0,0,9736586,30500,0,0,0,1,0,0,0,0,0,1,0,0,0
14,15519267,18700,1,0,15519267,18700,1,0,0,1,0,0,0,1,0,0,0,0,0
15,5367206,21000,1,1,5367206,21000,1,1,0,1,0,0,0,0,0,0,0,1,0
16,5367206,21000,1,1,5367206,21000,1,1,0,1,0,0,0,0,0,0,0,0,1
17,10782810,26500,0,1,10782810,26500,0,1,0,1,0,0,0,0,0,0,1,0,0
18,3331000,23200,0,1,3331000,23200,0,1,0,1,0,0,1,0,0,0,0,0,0
19,2870733,8000,0,1,2870733,8000,0,1,0,1,0,0,0,0,1,0,0,0,0
20,5635127,20200,0,1,5635127,20200,0,1,0,1,0,0,0,0,0,1,0,0,0
21,14862000,11300,0,1,14862000,11300,0,1,0,1,0,0,0,1,0,0,0,0,0
22,883305,15600,0,0,883305,15600,0,0,0,1,0,0,0,0,0,0,0,1,0
23,14910352,33900,0,0,14910352,33900,0,0,0,1,0,0,0,0,0,0,0,0,1
24,2581079,12900,0,1,2581079,12900,0,1,0,1,0,0,0,0,0,0,1,0,0
25,31400000,26700,1,1,31400000,26700,1,1,0,0,1,0,1,0,0,0,0,0,0
26,31400000,26700,1,1,31400000,26700,1,1,0,0,1,0,0,0,1,0,0,0,0
27,2693976,34600,0,0,2693976,34600,0,0,0,0,1,0,0,0,0,1,0,0,0
28,76750000,8400,1,1,76750000,8400,1,1,0,0,1,0,0,1,0,0,0,0,0
29,9751717,8400,0,0,9751717,8400,0,0,0,0,1,0,0,0,0,0,0,1,0
30,1793579,18300,0,1,1793579,18300,0,1,0,0,1,0,0,0,0,0,0,0,1
31,4397073,29100,1,1,4397073,29100,1,1,0,0,0,1,0,0,0,0,1,0,0
32,4397073,26400,1,0,4397073,26400,1,0,0,0,0,1,1,0,0,0,0,0,0
33,3520031,33900,0,0,3520031,33900,0,0,0,0,0,1,0,0,1,0,0,0,0
34,7592871,15600,0,0,7592871,15600,0,0,0,0,0,1,0,0,0,1,0,0,0
35,1808000,15000,0,1,1808000,15000,0,1,0,0,0,1,0,1,0,0,0,0,0
36,794128,21000,0,0,794128,21000,0,0,0,0,0,1,0,0,0,0,0,1,0
37,7592871,28500,1,1,7592871,28500,1,1,1,0,0,0,0,0,0,0,0,0,1
38,7592871,28500,1,1,7592871,28500,1,1,1,0,0,0,0,0,0,0,1,0,0
39,13698000,28500,1,1,13698000,28500,1,1,1,0,0,0,1,0,0,0,0,0,0
40,13698000,23200,1,1,13698000,23200,1,1,1,0,0,0,0,0,1,0,0,0,0
41,13698000,23200,1,0,13698000,23200,1,0,1,0,0,0,0,0,0,1,0,0,0

In [11]:
x = df4.drop(['Sold Out'],axis=1)

In [12]:
y = df4['Sold Out']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [15]:
from sklearn.naive_bayes import GaussianNB

In [19]:
gnb = GaussianNB()

In [21]:
gnb.fit(x_train,y_train)

GaussianNB()

In [22]:
y_pred = gnb.predict(x_test)

In [23]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test,y_pred))

ValueError: Classification metrics can't handle a mix of multilabel-indicator and binary targets